config/routes.rb
Adipose::Application.routes.draw do
  resources :adipocytes do
    resources :comments
  end

  resources :adipocytes do
    resources :tags
  end

  resources :users
  
  get "search/index"

  resources :search do
    collection do
      post :wtf
    end
  end

  resources :adipocytes do
    collection do
      post :enable
    end
  end

  resources :adipocytes do
    collection do
      post :castVote
    end
  end

  resources :adipocytes do
    collection do
      post :flagAdipocyte
    end
  end

  resources :comments do
    collection do
      post :create
    end
  end
  
  resources :comments do
    collection do
      post :delete
    end
  end

  resources :tags do
    collection do
      post :create
    end
  end

  resources :tags do
    collection do
      post :delete
    end
  end

  root :to => "search#index"

end

app/models/adipocyte.rb
class Adipocyte < ActiveRecord::Base
  has_many:comments
  has_many:tags
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :adipocyte
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :adipocyte
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/adipocytes_controller.rb
class AdipocytesController < ApplicationController
  # GET /adipocytes
  # GET /adipocytes.xml
  def index
  end

  # GET /adipocytes/1
  # GET /adipocytes/1.xml
  def show
    @adipocyte = Adipocyte.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @adipocyte }
    end
  end

  # GET /adipocytes/new
  # GET /adipocytes/new.xml
  def new
    @adipocyte = Adipocyte.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @adipocyte }
    end
  end

  # GET /adipocytes/1/edit
  def edit
    @adipocyte = Adipocyte.find(params[:id])
  end

  # POST /adipocytes
  # POST /adipocytes.xml
  def create
    @adipocyte = Adipocyte.new(params[:adipocyte])
    @adipocyte.update_attributes(:noVotes => 1, :enabled => true)

    respond_to do |format|
      if @adipocyte.save
        format.html { redirect_to(@adipocyte, :notice => 'Adipocyte was successfully created.') }
        format.xml  { render :xml => @adipocyte, :status => :created, :location => @adipocyte }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @adipocyte.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /adipocytes/1
  # PUT /adipocytes/1.xml
  def update
    @adipocyte = Adipocyte.find(params[:id])

    respond_to do |format|
      if @adipocyte.update_attributes(params[:adipocyte])
        format.html { redirect_to(@adipocyte, :notice => 'Adipocyte was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @adipocyte.errors, :status => :unprocessable_entity }
      end
    end
  end


  # PUT /adipocytes/castVote
  def castVote
    @adipocyte = Adipocyte.find(params[:id])
    numVotes = @adipocyte.noVotes + 1
    @adipocyte.update_attributes(:noVotes => numVotes)
    render :json => {:success => true, :numberOfVotes => numVotes}
  end
  
  # PUT /adipocytes/enable
  def enable
    @adipocyte = Adipocyte.find(params[:id])
    if(params[:enabled] == "1")
      @adipocyte.update_attributes(:enabled => false)
    else
      @adipocyte.update_attributes(:enabled => true)
    end
    render :json => {:success => true}
  end

  def flagAdipocyte
    @adipocyte = Adipocyte.find(params[:id])
    if(params[:flagged] == "1")
      @adipocyte.update_attributes(:flagged => false)
    else
      @adipocyte.update_attributes(:flagged => true)
    end
    render :json => {:success => true}
  end


  # DELETE /adipocytes/1
  # DELETE /adipocytes/1.xml
  def destroy
    @adipocyte = Adipocyte.find(params[:id])
    @adipocyte.destroy

    respond_to do |format|
      format.html { redirect_to(adipocytes_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @adipocyte = Adipocyte.find(params[:adipocyte_id])
    @comment = 
      @adipocyte.comments.create(
        :commenter => params[:commenter],
        :content => params[:content])
    render :json => 
      {:success => true, :commentId => @comment.id, :commenter => @comment.commenter}
  end
  
  def delete
    @comment = Comment.find(params[:id])
    @comment.destroy
    render :json => {:success => true}
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @adipocytes = Adipocyte.all(:order=>"created_at DESC", :limit=>"40")
    @flaggedAdipocytes = 
      Adipocyte.all(
        :conditions =>	{ :flagged => 1}) 
    @popularAdipocytes =
      Adipocyte.find(:all, :order=>"noVotes DESC", :limit=>"20")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @adipocytes, :xml => @flaggedAdipocytes, :xml => @popularAdipocytes}
    end
  end

  def wtf
    @adipocytes = 
      Adipocyte.all( 
        :conditions => ["userId = ? AND subject LIKE ?", 
          params[:user], 
          "%#{params[:subject]}%"])
   respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @adipocytes }
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController  
  def create
    @adipocyte = Adipocyte.find(params[:adipocyte_id])
    @tag = 
      @adipocyte.tags.create(
        :tag => params[:tag])
    render :json => 
      {:success => true, :tagId => @tag.id}
  end 


  def delete
    @tag = Tag.find(params[:id])
    @tag.destroy
    render :json => {:success => true}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/adipocytes_helper.rb
module AdipocytesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/adipocytes/_form.html.erb
<%= form_for(@adipocyte) do |f| %>
  <div class="adipocyteForm">
    <div class="formField">
      <%= f.label :userId %><br />
      <%= f.text_field :userId %>
    </div>
    <div class="formField">
      <%= f.label :subject %><br />
      <%= f.text_field :subject %>
    </div>
    <div class="formField">
      <%= f.label :content %><br />
      <%= f.text_area :content %>
    </div>
    <hr />
    <div class="actions">
      <%= f.submit %>
      <input 
        type="button" 
        id="adipocyteFormClearButton" 
        class="clearButton adiposeButton" 
        value="Clear">
    </div>
  </div><!--adipocyteForm-->
<% end %>
<script type="text/javascript">
</script>

app/views/adipocytes/edit.html.erb
<div class="contentPane">
  <div class="contentTitle adipocyteImage">
    <span class="adipocyteTitle">
      Edit Adipocyte
    </span>
  </div><!--.contentTitle-->
  <div class="contentBody">
    <%= render 'form' %>
  </div><!--.contentBody-->
</div><!--contentPane-->

app/views/adipocytes/index.html.erb
<h1>Listing adipocytes</h1>

<table>
  <tr>
    <th>Userid</th>
    <th>Subject</th>
    <th>Content</th>
    <th>Novotes</th>
    <th>Enabled</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @adipocytes.each do |adipocyte| %>
  <tr>
    <td><%= adipocyte.userId %></td>
    <td><%= adipocyte.subject %></td>
    <td><%= adipocyte.content %></td>
    <td><%= adipocyte.noVotes %></td>
    <td><%= adipocyte.enabled %></td>
    <td><%= link_to 'Show', adipocyte %></td>
    <td><%= link_to 'Edit', edit_adipocyte_path(adipocyte) %></td>
    <td><%= link_to 'Destroy', adipocyte, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Adipocyte', new_adipocyte_path %>

app/views/adipocytes/new.html.erb
<div class="contentPane">
  <div class="contentTitle adipocyteImage">
    <span class="adipocyteTitle">
      Create New Adipocyte
    </span>
  </div><!--.contentTitle-->
  <div class="contentBody">
    <%= render 'form' %>
  </div><!--.contentBody-->
</div><!--contentPane-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Adipose</title>
  <link type="text/css" href="/stylesheets/jquery-ui/development-bundle/themes/base/jquery.ui.all.css" rel="Stylesheet" /> 
  <link type="text/css" href="/stylesheets/jquery-ui/css/smoothness/jquery-ui-1.8.6.custom.css" rel="Stylesheet" /> 
  <script type="text/javascript" src="/javascripts/js/jquery-1.4.2.min.js"></script>
  <script type="text/javascript" src="/javascripts/js/jquery-ui-1.8.6.custom.min.js"></script>
  <%= stylesheet_link_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="custom-doc">
  <div id="header">
    <div id="headerTop">
    </div>
    <div id="headerImage">
    </div>
    <div id="headerTitle">
      Adipose
    </div>
    <div id="headerBottom">
      <span id="options">
        <span first="headerHomeOption">
          Home
        </span>
        <span id="headerLogoutOption">
          Logout
        </span>
      </span>
    </div>
  </div>
  <div id="bodyContent">
    <div id="recentViews">
      <span id="heading">
        Recent Views:
      </span>
    </div>
    <div id="menu">
      <ul id="quickAdd"> 
        <li class="menuItem image">
          Add
        </li>
        <li>
          <%= link_to 'New Adipocyte', new_adipocyte_path %>
        </li>
      </ul>
      <ul id="quickSearch"> 
        <% form_tag(
          {:controller =>"search", :action => "wtf"}, :id => "quickSearchForm") do %>
          <li class="menuItem image">
            Search
          </li>
          <li>
            <input 
              type="text" 
              value="Subject Contains" 
              name="subject" 
              id="quickSearchSubject"/>
          </li>
          <li>
            <input type="text" value="Username" name="user" id="quickSearchUser"/>
          </li>
        <% end %>
      </ul>
      <ul id="quickTools"> 
        <li class="menuItem image">
          Tools
        </li>
        <li>
          <a>
            Edit Settings
          </a>
        </li>
        <li>
          <a>
            Users
          </a>
        </li>
      </ul>
    </div><!--#menu-->
    <div id="body">
    
      <%= yield %>

    </div><!--#body-->
    <div id="notification">
    </div>
  </div><!--#bodyContent-->
  <div id="footer">
    &copy; Adipose 2010
  </div>
  <script type="text/javascript">
    function submitQuickSearchForm()
    {
     var keycode;
     if (window.event) 
       keyCode = window.event.keyCode;
     if( keyCode == 13)
       $("#quickSearchForm").submit();
    }
    
    function notify(title, message)
    { 
      $("#notification").attr("title",title);
      $("#notification").html(message);
      $("#notification").dialog(
      {
        modal: true,
        height:120,
        close: function(event,ui)
        {
          $("#notification").dialog("destroy");
        },
      });
    }

    function clearForm()
    {
      $(".formField :input").each(function(){
        $(this).val('');
      });
      $(".formField textarea").each(function(){
        $(this).val('');
      });
    }
 
    $(document).ready(function()
    {
      $("#quickSearchSubject").keypress(function()
      {
        submitQuickSearchForm();
      });

      $("#quickSearchUser").keypress(function()
      { 
        submitQuickSearchForm();
      });

      $("#quickSearchSubject").focus(function()
      {
        $(this).attr('value','');
      });

      $("#quickSearchUser").focus(function()
      {
        $(this).attr('value','');
      });

      $("#quickSearchSubject").blur(function()
      {
        if($.trim($(this).attr('value')) == "")
          $(this).attr('value','Subject Contains');
      });

      $("#quickSearchUser").blur(function()
      {
        if($.trim($(this).attr('value')) == "")
          $(this).attr('value','Username');
      });

      $("#header").click(function()
      {
        document.location = "/";
      });      

      $("#headerHomeOption").click(function()
      {
        document.location = "/";
      });      

      $(".clearButton").click(function(){
        clearForm();
      });
    });
  </script>
</div><!--#custom-doc-->
</body>
</html>

app/views/search/index.html.erb
<div class="contentPane">
  <div class="contentTitle newAdipocytesImage">
    Adipocytes
  </div><!--#contentTitle-->
  <div class="contentBody">
    <div id="tabs">
      <ul>
        <li>
          <a href="#recentAdipocytesTab">Recent</a>
        </li>
        <li>
          <a href="#popularAdipocytesTab">Popular</a>
        </li>
        <li>
          <a href="#flaggedAdipocytesTab">Flagged</a>
        </li>
      </ul>
      <div id="recentAdipocytesTab">
        <div class="newAdipocytesOptionsDiv">
          <%= select(
            'newAdipocytesOptions',
            'optionId',
              [["Select Action","-1"],["Archive","1"],["Unarchive","2"],["Flag","3"],["Unflag","4"],["Tag","5"],["Untag","6"],["Download","7"]])%>  
        </div><!--newAdipocytesOptinsDiv-->
        <div class="listAdipocytes">
          <table class="searchResults">
            <tr>
              <th>
                <%= check_box_tag "selectAllNewAdipocytes" %>
              </th>
              <th>Created By</th>
              <th>Subject</th>
              <th>Created On</th>
              <th>Votes</th>
            </tr>
            <% @adipocytes.each do |adipocyte| %>
              <% if adipocyte.enabled %>
                <% rowEnabled = "enabled votesEnabled" %>
              <% else %>
                <% rowEnabled = "disabled" %>
              <% end %>
              <tr class="<%= rowEnabled%> searchResult" data-id="<%= adipocyte.id %>">
                <td>
                  <%= check_box_tag (
                    "newAdipocyte"+adipocyte.id.to_s,
                    "yes",
                    false,
                    :class=>"newAdipocyte", 
                    :"data-id"=>adipocyte.id) %>
                </td>
                <td class="toAdipocytePage"><%= adipocyte.userId %></td>
                <td class="toAdipocytePage"><%= adipocyte.subject %></td>
                <td class="toAdipocytePage">
                  <%= adipocyte.created_at.to_s(format = :short)%>
                </td>
                <% if adipocyte.enabled %>
                  <% colEnabled = 'votesGreen votesSummary' %>
                <% else %>
                  <% colEnabled = 'votesSummary' %>
                <% end %>
                <td class="<%= colEnabled %>">
                  <%= adipocyte.noVotes %>
                </td>
              </tr>
            <% end %>
          </table>
        </div><!--#listAdipocytes-->
      </div><!--#recentAdipocytesTab-->
      <div id="flaggedAdipocytesTab">
        <div class="flaggedAdipocytesOptionsDiv">
          <%= select(
            'flaggedAdipocytesOptions',
            'optionId',
              [["Select Action","-1"],["Unflag","1"],["Download","2"]])%>  
        </div><!--.flaggedAdipocytesOptinsDiv-->
        <div class="listFlaggedAdipocytes">
          <table class="searchResults">
            <tr>
              <th>
                <%= check_box_tag "selectAllFlaggedAdipocytes" %>
              </th>
              <th>Created By</th>
              <th>Subject</th>
              <th>Created On</th>
              <th>Votes</th>
            </tr>
            <% @flaggedAdipocytes.each do |adipocyte| %>
              <% if adipocyte.enabled %>
                <% rowEnabled = "enabled votesEnabled" %>
              <% else %>
                <% rowEnabled = "disabled" %>
              <% end %>
              <tr class="<%= rowEnabled%> searchResult" data-id="<%= adipocyte.id %>">
                <td>
                  <%= check_box_tag (
                    "flaggedAdipocyte"+adipocyte.id.to_s,
                    "yes",
                    false,
                    :class=>"flaggedAdipocyte", 
                    :"data-id"=>adipocyte.id) %>
                </td>
                <td class="toAdipocytePage"><%= adipocyte.userId %></td>
                <td class="toAdipocytePage"><%= adipocyte.subject %></td>
                <td class="toAdipocytePage">
                  <%= adipocyte.created_at.to_s(format = :short)%>
                </td>
                <% if adipocyte.enabled %>
                  <% colEnabled = 'votesGreen votesSummary' %>
                <% else %>
                  <% colEnabled = 'votesSummary' %>
                <% end %>
                <td class="<%= colEnabled %>">
                  <%= adipocyte.noVotes %>
                </td>
              </tr>
            <% end %>
          </table>
        </div><!--#listFlaggedAdipocytes-->
      </div><!--#flaggedAdipocytesTab-->
      <div id="popularAdipocytesTab">
        <div class="popularAdipocytesOptionsDiv">
          <%= select(
            'newAdipocytesOptions',
            'optionId',
              [["Select Action","-1"],["Archive","1"],["Unarchive","2"],["Flag","3"],["Unflag","4"],["Tag","5"],["Untag","6"],["Download","7"]])%>  
        </div><!--.popularAdipocytesOptinsDiv-->
        <div class="popularAdipocytes">
          <table class="searchResults">
            <tr>
              <th>
                <%= check_box_tag "selectAllPopularAdipocytes" %>
              </th>
              <th>Created By</th>
              <th>Subject</th>
              <th>Created On</th>
              <th>Votes</th>
            </tr>
            <% @popularAdipocytes.each do |adipocyte| %>
              <% if adipocyte.enabled %>
                <% rowEnabled = "enabled votesEnabled" %>
              <% else %>
                <% rowEnabled = "disabled" %>
              <% end %>
              <tr class="<%= rowEnabled%> searchResult" data-id="<%= adipocyte.id %>">
                <td>
                  <%= check_box_tag (
                    "popularAdipocyte"+adipocyte.id.to_s,
                    "yes",
                    false,
                    :class=>"popularAdipocyte", 
                    :"data-id"=>adipocyte.id) %>
                </td>
                <td class="toAdipocytePage"><%= adipocyte.userId %></td>
                <td class="toAdipocytePage"><%= adipocyte.subject %></td>
                <td class="toAdipocytePage">
                  <%= adipocyte.created_at.to_s(format = :short)%>
                </td>
                <% if adipocyte.enabled %>
                  <% colEnabled = 'votesGreen votesSummary' %>
                <% else %>
                  <% colEnabled = 'votesSummary' %>
                <% end %>
                <td class="<%= colEnabled %>">
                  <%= adipocyte.noVotes %>
                </td>
              </tr>
            <% end %>
          </table>
        </div><!--.popularAdipocytes-->
      </div><!--#popularAdipocytesTab-->
    </div><!--#tabs-->
  </div><!--.contentBody-->
</div><!--.contentPane-->
<script type="text/javascript">
  $(document).ready(function()
  {
    $("#tabs").tabs();

    $(".toAdipocytePage").click(function(){
      document.location = "/adipocytes/"+$(this).parent().attr('data-id');
    });
  });
</script>

app/views/search/wtf.html.erb
<div class="contentPane">
  <div class="contentTitle newAdipocytesImage">
    Search Adipocytes
  </div><!--#contentTitle-->
  <div class="contentBody">
    <div>
      <% form_tag(:action => "wtf") do %>
        <div class="formField">
          <%= text_field_tag(:subject,"Subject Contains") %>
          <%= text_field_tag(:user,"username") %>
          <%= submit_tag("Search") %>
        </div><!--formField-->
      <% end %>
    </div>
    <div class="listAdiposts">
      <table class="searchResults">
        <tr>
          <th>Created By</th>
          <th>Subject</th>
          <th>Created On</th>
          <th>Votes</th>
        </tr>
        <% @adipocytes.each do |adipocyte| %>
          <% if adipocyte.enabled %>
            <% rowEnabled = "enabled votesEnabled" %>
          <% else %>
            <% rowEnabled = "disabled" %>
          <% end %>
          <tr class="<%= rowEnabled%> searchResult" data-id="<%= adipocyte.id %>">
            <td><%= adipocyte.userId %></td>
            <td><%= adipocyte.subject %></td>
            <td>
              <%= adipocyte.created_at.to_s(format = :short)%>
            </td>
            <% if adipocyte.enabled %>
              <% colEnabled = 'votesGreen votesSummary' %>
            <% else %>
              <% colEnabled = 'votesSummary' %>
            <% end %>
            <td class="<%= colEnabled %>">
              <%= adipocyte.noVotes %>
            </td>
          </tr>
        <% end %>
      </table>
    </div><!--#listAdiposts-->
  </div><!--.contentBody-->
</div><!--.contentPane-->
<script type="text/javascript">
  $(document).ready(function()
  {
    $(".searchResult").click(function(){
      document.location = "/adipocytes/"+$(this).attr('data-id');
    });

    $("#subject").focus(function()
    {
      $(this).attr('value','');
    });

    $("#user").focus(function()
    {
      $(this).attr('value','');
    });

    $("#subject").blur(function()
    {
      if($.trim($(this).attr('value')) == "")
        $(this).attr('value','Subject Contains');
    });

    $("#user").blur(function()
    {
      if($.trim($(this).attr('value')) == "")
        $(this).attr('value','Username');
    });
  });
</script>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>